x-common-config: &common-config
  network_mode: host
  ipc: host
  restart: always
  environment:
    - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp # Default FastDDS do not work
    - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
    # - ROBOT_NAMESPACE=panther

services:
  luxonis:
    image: husarion/depthai:humble-v2.10.3
    <<: *common-config
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ./config/depthai.yaml:/config.yaml
      - ./config/oak_d_pro_wide_calibration.yaml:/calibration.yaml
    device_cgroup_rules:
      - "c 189:* rmw"
    command: >
      ros2 launch depthai_ros_driver camera.launch.py
        params_file:=/config.yaml
        parent_frame:=panther/front_bumper_link
        cam_pos_z:=-0.035

  apriltag:
    image: husarion/apriltag:humble-ros2-husarion-utils
    <<: *common-config
    volumes:
      - ./config/apriltag.yaml:/apriltag.yaml
    command: >
      ros2 launch /husarion_utils/apriltag.launch.py apriltag_config_path:=/apriltag.yaml
      namespace:=panther
      camera_image_topic:=/oak/rgb/image_raw
      camera_info_topic:=/oak/rgb/camera_info
      apriltag_detections_topic:=apriltag/detections
